##
# i recommend researching and testing with `sysctl(8)` before doing anything here for safety, there are tons of parameters to explore.
#
# shared memory is a method of sharing a common memory space for inter-process communication (IPC)
# modern browsers, multimedia apps, databases, games, containers, vms
#
kern.shminfo.shmall=3145728 # total number of pages, 1 page per 4096 bytes. ill put 1966080 pages for my 8gb tp ((8GB-512M)/4096)
kern.shminfo.shmmax=536870912  # cap for each shm segment, for safety, ill set it dividing my memory by 16. 512mb is enough (db shared_buffer, browser cache).
kern.shminfo.shmmni=2048 # max number of segments in a system (enough space for multitasks, containers, vms)
kern.shminfo.shmseg=2048 # max number of segments a single process can attach to (allows browsers/multimedia with many tabs/processes use multiple segments)
#
# IPC semaphores (sync between processes)
kern.seminfo.semmns=4096 # total semaphores
kern.seminfo.semmni=1024 # total sets of semaphores, 1024 x average semaphores per set should equal to SEMMNS
#
# Max processes and open file descriptors (enough for me. browsers, compiling, multitasking)
kern.maxproc=32768
kern.maxfiles=65535
#
# Vnode is a kernel abstraction of a file system, it represents a file system object (good for caching)
kern.maxvnodes=262144 # max tracked filesystem objects by the kernel (open files, dirs, sockets, etc.)
#
# Network tuning
kern.somaxconn=2048 # max number of pending TCP connections in listen queue (useful on p2p, modern browsers open tons of connections), 1024 feels enough for me
net.inet.udp.recvspace=262144 # UDP receive and send buffers, useful for streaming and calls
net.inet.udp.sendspace=262144
net.inet.tcp.mssdflt=1460 # default TCP MSS to ethernet MTU
net.inet.tcp.keepidle=300 # reduce idle keepalive time to detect dead connections faster
net.inet.ip.ifq.maxlen=4096 # increase interface queue max length for better burst handling
net.inet6.ip6.ifq.maxlen=4096 # for ipv6
#
hw.smt=1 # enable hyperthreading, check https://www.openbsd.org/faq/faq10.html before
#
kern.bufcachepercent=90

